const express = require("express")
const router = express.Router()
const controller = require("./controllers/controller")

router.post("/login", controller.LogIn)
router.get("/users",controller.getUsers)
router.get("/adresses",controller.getAdress)
router.post("/adduser", controller.AddUser)
router.post("/becomeparticipant", controller.becomeParticipant)

//do strzelania
router.post("/getmyevents", controller.getMyEvents)
router.post("/getmyeventsparticipants", controller.getMyEventsParticipants)
router.get("/currentevents", controller.currentEvents)
router.post("/currentsportevents", controller.currentSportEvents)
router.post("/addcourtfrommap", controller.AddCourtFromMap)
router.get("/courts", controller.getCourts)
router.post("/sportcourts", controller.getSportCourts)
router.post("/becomeparticipant", controller.becomeParticipant)
router.post("/createdevents", controller.createdEvents)
router.post("/kickplayer", controller.kickPlayer)
router.post("/createnewevent", controller.AddEventFromMap)
router.post("/destroyaccount", controller.destroyAccount)
router.post("/ispasswordcorrect", controller.isPasswordCorrect)
router.post("/changepassword", controller.changePassword)
router.post("/changeemail", controller.changeEmail)
router.post("/eventsfromcourt", controller.getEventsFromCourt)
router.post("/markparticipants", controller.markParticipants)
module.exports = router